<?php

namespace Database\Factories;

use App\Models\Inventory;
use App\Models\Laboratorium;
use App\Models\PCDetail;
use App\Models\NonPCDetail;
use App\Models\SoftwareDetail;
use Illuminate\Database\Eloquent\Factories\Factory;

class InventoryFactory extends Factory
{
    protected $model = Inventory::class;

    public function definition(): array
    {
        // Kode inventaris will be auto-generated in the model's boot method
        return [
            'laboratorium_id' => Laboratorium::factory(),
            'kode_inventaris' => null, // Will be auto-generated by the model
            'nama_barang' => fake()->words(2, true),
            'kondisi' => fake()->randomElement(['Baik', 'Rusak Ringan', 'Rusak Berat', 'Dalam Perbaikan']),
            'tanggal_pengadaan' => fake()->dateTimeBetween('-1 year', 'now')->format('Y-m-d'),
            'inventoriable_id' => null, // Will be set after related models are created
            'inventoriable_type' => null, // Will be set after related models are created
        ];
    }

    /**
     * Configure the factory to create a PC inventory.
     */
    public function forPC(): Factory
    {
        return $this->state(function (array $attributes) {
            $pcDetail = PCDetail::factory()->create();

            return [
                'inventoriable_id' => $pcDetail->id,
                'inventoriable_type' => 'App\Models\PCDetail',
            ];
        });
    }

    /**
     * Configure the factory to create a Non-PC inventory.
     */
    public function forNonPC(): Factory
    {
        return $this->state(function (array $attributes) {
            $nonPCDetail = NonPCDetail::factory()->create();

            return [
                'inventoriable_id' => $nonPCDetail->id,
                'inventoriable_type' => 'App\Models\NonPCDetail',
            ];
        });
    }

    /**
     * Configure the factory to create a Software inventory.
     */
    public function forSoftware(): Factory
    {
        return $this->state(function (array $attributes) {
            $softwareDetail = SoftwareDetail::factory()->create();

            return [
                'inventoriable_id' => $softwareDetail->id,
                'inventoriable_type' => 'App\Models\SoftwareDetail',
            ];
        });
    }
}
